### ISSUE TITLE
Increase JVM memory on windows

### ISSUE THREAD

**Issue by kikohs** [wjrl/BioFabric#138]
Hi there,
I've been trying to use BioFabric but ran into JVM memory issues several times. How do you easily change the amount of RAM on the embedded JRE?
Thanks

**Comment by wlongabaugh** [comment]
Are you using the Version 2 Beta or the old production Version 1? And what platform are you on (Mac, Windows, Linus)?

**Comment by kikohs** [comment]
Windows, version 2 beta.

**Comment by wlongabaugh** [comment]
OK, the maximum memory limit is hardcoded inside the .exe file. My suggestion is to download the Linux version, which has a Java jar file. Then, you can run a Windows batch script which uses the Java runtime from the Windows version, pointing to the Linux jar file, and specify the maximum memory size on the command line. E.g., if your Windows BioFabric exe is in `C:\users\kikohs\Desktop\BioFabric` and the Linux version is in `C:\users\kikohs\Desktop\BioFabricLinux` you would run this command from the Command Prompt:
```
C:\users\kikohs\Desktop\BioFabric\lib\win-jre-12.0.1\bin\java.exe -Xmx32000m -jar  C:\users\kikohs\Desktop\BioFabricLinux\lib\sBioFabric-V2.0.B.2.jar
```
to get 32G of memory. How much RAM does your system have? Because if the memory specified is greater than your RAM, performance will be really poor.

Could you let me know how many nodes and edges you have in your network? And also what memory requirements you end up needing?

Sorry this is kinda complex. If you let me know the above info, I can create a large-memory version at some point when I get the chance.

**Comment by kikohs** [comment]
Perfect, I'll try that tomorrow. I have 64 GiB memory. I don't have a specific network in mind. I do artistic renders of networks and was wondering if BioFabric could yield interesting shapes.

I usually use graphml or gexf graphs but I am not familiar with BioFabric data format. My end goal here is to export the layout as a  PNG file. 
Can I use any of the above file formats? Otherwise can I use Cytoscape and export to a BioFabric compatible file format?

**Comment by wlongabaugh** [comment]
Your best bet is to create a SIF file with a line for each edge: `node1<tab>edge_label<tab>node2`.
Then import the SIF. If you save it out, it will be as a BIF file, which is XML.

**Comment by wlongabaugh** [comment]
I will leave this ticket open until I hear you are up and running.

**Comment by kikohs** [comment]
It works! Thanks for the help.
